export const mymenus = [{
  id: '08',
  path: '/video',
  title: '视频监控',
  component: 'layout/Layout',
  children: [{
    id: '0840',
    path: '',
    icon: 'calOperate',
    title: '视频监控',
    component: '',
    children: [{
      id: '0841',
      path: 'trolook',
      title: '监控查看',
      component: 'graph/trolook/index'
    }]
  }]
}, {
  id: '0',
  parentId: null,
  path: '/admin',
  title: '档案管理',
  component: 'layout/Layout',
  sortNum: 0,
  children: [{
    id: '10100',
    parentId: '0',
    path: '',
    icon: 'msgOperate',
    title: '老人信息管理',
    component: '',
    sortNum: 0,
    children: [{
      id: '10110',
      parentId: '10100',
      path: 'elder',
      title: '老人信息查询',
      component: 'dossier/elder/index',
      buttonList: [{
        id: '1',
        menuId: '10110',
        buttonName: '添加',
        type: 'addBtn',
        sortNum: 0
      }, {
        id: '2',
        menuId: '10110',
        buttonName: '修改',
        type: 'editBtn',
        sortNum: 0
      }, {
        id: '3',
        menuId: '10110',
        buttonName: '删除',
        type: 'delBtn',
        sortNum: 0
      }, {
        id: '4',
        menuId: '10110',
        buttonName: '批量导入',
        type: 'lotBtn',
        sortNum: 0
      }, {
        id: '5',
        menuId: '10110',
        buttonName: '导出',
        type: 'outBtn',
        sortNum: 0
      }, {
        id: '6',
        menuId: '10110',
        buttonName: '查看详情',
        type: 'detailBtn',
        sortNum: 0
      }],
      sortNum: 0
    }]
  }, {
    id: '10300',
    parentId: '0',
    path: '',
    icon: 'sysOperate',
    title: '权限管理',
    component: '',
    sortNum: 0,
    children: [{
      id: '10320',
      parentId: '10300',
      path: 'menu',
      title: '菜单维护',
      component: 'mgr/menu/index',
      sortNum: 0
    }, {
      id: '10330',
      parentId: '10300',
      path: 'press',
      title: '按钮维护',
      component: 'mgr/press/index',
      sortNum: 0
    }, {
      id: '10340',
      parentId: '10300',
      path: 'role',
      title: '角色维护',
      component: 'mgr/role/index',
      sortNum: 0
    }, {
      id: '10360',
      parentId: '10300',
      path: 'dic',
      title: '字典维护',
      component: 'mgr/dic/index',
      sortNum: 0
    }]
  }]
}]
